services:

  backend:

    build:
      context: ..
      dockerfile: docker/backend/Dockerfile

    container_name: backend

    ports:
      - "9000:9000"

    environment:
      APP_ENV: Development

  frontend:

    build:
      context: ..
      dockerfile: docker/frontend/Dockerfile

    container_name: frontend

    ports:
      - "8080:80"

    depends_on:
      - backend