apiVersion: apps/v1
kind: Deployment

metadata:
  name: backend
  namespace: dev

spec:
  replicas: 2

  selector:
    matchLabels:
      app: backend

  template:

    metadata:
      labels:
        app: backend

    spec:

      containers:

      - name: backend

        image: cloudwithnitesh/cloudops-backend:1.0

        ports:
        - containerPort: 9000

        env:
        - name: APP_ENV
          value: Development