pipeline {

    agent any

    stages {

        stage('Repository') {
            steps {

                echo "Repository cloned successfully"

                sh "pwd"

                sh "ls -la"

            }
        }

        stage('Backend Files') {
            steps {

                sh "ls -la application"

                sh "ls -la application/backend"

            }
        }

    }

}